from paver.easy import consume_args, needs, sh, task

from distutils.dir_util import copy_tree, mkpath, remove_tree
from distutils.file_util import copy_file

@task
@needs(['deps', 'migrate'])
@consume_args
def setup(args):
    """Setups the project."""
    sh('bower install')
    sh('npm install --save-dev')
    sh('gulp')

@task
@needs(['clean'])
def build():
    build_dir = 'build'
    remove_tree(build_dir)
    mkpath(build_dir)
    copy_tree('rotina/static', '%s/static' % build_dir)
    copy_file('rotina/templates/index.html', build_dir)

@task
def clean():
    """Removes files generated by build or runtime."""
    sh("find . -name '*.pyc' -print0 | xargs -0 rm")

@task
@consume_args
def deps(args):
    """Installs the required dependencies for an environment: dev, test, or prod."""
    sh('pip install -q -r requirements/%s.txt' % get_env(args))

@task
def migrate():
    """Synchronizes the database according to migrations."""
    sh_manage("migrate")

@task
def shell():
    sh_manage('shell_plus --ipython')

@task
@needs(['deps'])
@consume_args
def run(args):
    """Runs the development web server on port 8000."""
    sh_manage('runserver_plus 0.0.0.0:8000 --settings=rotina.settings.%s' % get_env(args))

def sh_manage(command, capture=False):
    """Runs a shell command through Django's manage.py."""
    return sh("python manage.py %s" % command, capture=capture)

def get_env(args):
    return args[0] if args else 'dev'
